server:
  port: 8080
  error:
    include:
      message: true

spring:
  application:
    name: rococo-gateway

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG

---
spring:
  config:
    activate:
      on-profile: 'local'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://127.0.0.1:9000'
  graphql:
    graphiql:
      enabled: true

rococo-painting:
  base-uri: 'http://127.0.0.1:8085'
rococo-artist:
  base-uri: 'http://127.0.0.1:8086'
rococo-geo:
  base-uri: 'http://127.0.0.1:8087'
rococo-museum:
  base-uri: 'http://127.0.0.1:8088'
rococo-userdata:
  base-uri: 'http://127.0.0.1:8089'
rococo-front:
  base-uri: 'http://127.0.0.1:3000'

---
spring:
  config:
    activate:
      on-profile: 'docker'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://auth.rococo.dc:9000'

rococo-painting:
  base-uri: 'http://painting.rococo.dc:8085'
rococo-museum:
  base-uri: 'http://museum.rococo.dc:8088'
rococo-artist:
  base-uri: 'http://artist.rococo.dc:8086'
rococo-geo:
  base-uri: 'http://geo.rococo.dc:8087'
rococo-userdata:
  base-uri: 'http://userdata.rococo.dc:8089'
rococo-gateway:
  base-uri: 'http://api.rococo.dc:8080'
rococo-front:
  base-uri: 'http://client.rococo.dc'
---