version: '3.9'

services:

  selenoid:
    container_name: selenoid
    image: aerokube/selenoid:1.10.12
    volumes:
      - ./selenoid:/etc/selenoid
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: [ "-conf", "/etc/selenoid/browsers.json", "-limit", "1", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "rococo_test-network" ]
    ports:
      - "4444:4444"
    networks:
      - test-network
    dns_search: .

  selenoid-ui:
    container_name: selenoid-ui
    image: aerokube/selenoid-ui:1.10.9
    depends_on:
      - selenoid
    restart: unless-stopped
    ports:
      - "9090:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]
    networks:
      - test-network
    dns_search: .

  chrome:
    container_name: chrome
    image: selenoid/vnc:chrome_110.0
    depends_on:
      - selenoid
    restart: unless-stopped
    ports:
      - "5678:5678"
    networks:
      - test-network
    dns_search: .


networks:
  test-network:
    driver: bridge
